version: '3.8'

services:
  petclinic:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: petclinic-app
    restart: always
    ports:
      - "8081:8080"
    networks:
      - petclinic-network

networks:
  petclinic-network:
    driver: bridge
